services:
  db:
    image: postgres:16
    container_name: forrealbank-db
    restart: unless-stopped
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4
    container_name: forrealbank-pgadmin
    restart: unless-stopped
    env_file:
      - ./env/pgadmin.env
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    user: "0"

  api:
    build:
      context: .
      dockerfile: apps/api-nest/Dockerfile
    container_name: forrealbank-api
    restart: unless-stopped
    env_file:
      - ./env/api.env
    command: pnpm start:dev
    volumes:
      - ./apps/api-nest:/usr/src/app/apps/api-nest
      - /usr/src/app/apps/api-nest/node_modules
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
  web:
    build:
      context: .
      dockerfile: apps/web-next/Dockerfile
    container_name: forrealbank-web
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api

volumes:
  dbdata:
  pgadmin_data: